// <auto-generated />
namespace SoNWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2ndattemptataccountcontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2ndattemptataccountcontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "201703040611121_2ndattemptataccountcontroller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
